# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de101c8cb916c02303be8f7bb71375d8e5ae33e545d4179c7e4f2eda44c1a569c98f0f5decea2fd61ac0848cc2ffd4a648f22fd30398c5112cf905e8d82bee09

test:
  secret_key_base: f52c2ffdcf5d0f898b6c1e74770006f14376d34c8b389aa5288d391e89bcb2679ea8c18db579189e2e7514b1a46d745c1fe98635689a2c65bfd78c6f2dce756d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
